name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Node + pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm               # 缓存 ~/.pnpm-store

      - name: Install Dependencies
        run: |
          corepack enable           # 启用 pnpm
          pnpm install --frozen-lockfile

      # 3️⃣ Build (先生成临时 TaskXX.md)
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm run gen:task         # ← scripts/gen-task-md.js
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      # 4️⃣ Deploy
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: blog_pages
          folder: src/.vuepress/dist
