# .github/workflows/deploy-docs.yml
name: Deploy Docs
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm            # ← 改成 pnpm
      - name: Install pnpm
        run: corepack enable && pnpm --version   # corepack 会自动安装 pnpm 8+

      - name: Install deps
        run: pnpm install --frozen-lockfile      # 读取 pnpm-lock.yaml

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build && touch src/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: blog_pages
          folder: src/.vuepress/dist
