name: Deploy Docs
on:
  push: { branches: [main] }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # (可选) 新 cache key，防旧缓存
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      # DEBUG —— 看看 CI 拿到的锁文件是啥
      - name: Debug | show lockfile header
        run: head -n 15 pnpm-lock.yaml || true

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env: { NODE_OPTIONS: --max_old_space_size=8192 }
        run: pnpm docs:build && touch src/.vuepress/dist/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: blog_pages
          folder: src/.vuepress/dist
